# Generated by Django 2.2.5 on 2019-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic', models.ImageField(upload_to='', verbose_name='pictures/')),
                ('example_page1', models.ImageField(blank=True, upload_to='example_pages/')),
                ('example_page2', models.ImageField(blank=True, upload_to='example_pages/')),
                ('example_page3', models.ImageField(blank=True, upload_to='example_pages/')),
            ],
        ),
    ]
