# Generated by Django 2.2.5 on 2019-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190918_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09123456789', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
